#!/usr/bin/env bash
# generate-olla-config.sh
#
# Generates olla.yaml from OLLAMA_REMOTE_* entries in .env.
# Run this script manually: bash scripts/generate-olla-config.sh
# It is also called automatically by start.sh on each stack start.
#
# Remote node format in .env:
#   OLLAMA_REMOTE_<NAME>=http://host:port[:priority]
#
#   Priority is optional (defaults to 70).
#   NAME can be alphanumeric + underscores.
#
# Examples:
#   OLLAMA_REMOTE_WORKSTATION=http://192.168.1.50:11434:75
#   OLLAMA_REMOTE_NAS=http://192.168.1.51:11434
#
# Fixed nodes (always present, configurable priority):
#   priority 70 (default) — ollama  (local Ollama node — Arc, NVIDIA, or CPU)
#   priority 50           — litellm (cloud gateway: Claude, Gemini)
#
# Advanced tuning (optional .env vars):
#   OLLA_ENGINE            — "sherpa" (default) or "olla"
#   OLLA_LOAD_BALANCER     — "least-connections" (default), "round-robin", "priority"
#   OLLA_REQUEST_LOGGING   — true (default) or false
#   OLLA_LOCAL_PRIORITY    — local Ollama node priority (default: 70)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${SCRIPT_DIR}/../proxy/olla.yaml"
ENV_FILE="${SCRIPT_DIR}/../.env"

# ── Load .env ──────────────────────────────────────────────────────────────────
# Parse only OLLA_* and OLLAMA_REMOTE_* vars to avoid sourcing the entire file
# (which could fail on special characters in API keys).
if [[ -f "$ENV_FILE" ]]; then
  while IFS='=' read -r key val || [[ -n "$key" ]]; do
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [[ -z "$key" ]] && continue
    val="${val%%#*}"
    val="$(echo "$val" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    val="${val#\"}"; val="${val%\"}"
    val="${val#\'}"; val="${val%\'}"
    case "$key" in
      OLLA_*|OLLAMA_REMOTE_*)
        declare -gx "$key=$val"
        ;;
    esac
  done < "$ENV_FILE"
fi

OLLA_ENGINE="${OLLA_ENGINE:-sherpa}"
OLLA_LOAD_BALANCER="${OLLA_LOAD_BALANCER:-least-connections}"
OLLA_REQUEST_LOGGING="${OLLA_REQUEST_LOGGING:-true}"
OLLA_LOCAL_PRIORITY="${OLLA_LOCAL_PRIORITY:-70}"

# ── Collect OLLAMA_REMOTE_* entries ────────────────────────────────────────────
declare -A REMOTE_URLS=()
declare -A REMOTE_PRIORITIES=()

if [[ -f "$ENV_FILE" ]]; then
  while IFS='=' read -r key val; do
    [[ "$key" =~ ^OLLAMA_REMOTE_([A-Za-z0-9_]+)$ ]] || continue
    name="${BASH_REMATCH[1]}"
    val="${val%%#*}"; val="${val#"${val%%[![:space:]]*}"}"; val="${val%"${val##*[![:space:]]}"}"
    [[ -n "$val" ]] || continue
    # Parse format: url:port[:priority]
    if [[ "$val" =~ ^(.*:[0-9]+):([0-9]+)$ ]]; then
      # Three-part: url:port:priority
      REMOTE_URLS["$name"]="${BASH_REMATCH[1]}"
      REMOTE_PRIORITIES["$name"]="${BASH_REMATCH[2]}"
    elif [[ "$val" =~ ^.*:[0-9]+$ ]]; then
      # Two-part: url:port (no explicit priority)
      REMOTE_URLS["$name"]="$val"
      priority_var="OLLAMA_REMOTE_${name}_PRIORITY"
      REMOTE_PRIORITIES["$name"]="${!priority_var:-70}"
    else
      # Bare URL: only host, no port
      REMOTE_URLS["$name"]="$val"
      priority_var="OLLAMA_REMOTE_${name}_PRIORITY"
      REMOTE_PRIORITIES["$name"]="${!priority_var:-70}"
    fi
  done < "$ENV_FILE"
fi

echo "→ Generating olla.yaml..."
if [[ ${#REMOTE_URLS[@]} -eq 0 ]]; then
  echo "   (no OLLAMA_REMOTE_* entries found — only local Ollama node + LiteLLM)"
fi

# ── Write olla.yaml ────────────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
# olla.yaml — AUTO-GENERATED by generate-olla-config.sh
# Do not edit directly. Edit .env and re-run generate-olla-config.sh (or start.sh).
# This file is in .gitignore — LAN node addresses stay off the repo.

server:
  host: "0.0.0.0"
  port: 40114
  request_logging: ${OLLA_REQUEST_LOGGING}
  write_timeout: 600s

proxy:
  engine: "${OLLA_ENGINE}"
  load_balancer: "${OLLA_LOAD_BALANCER}"
  response_timeout: 600s
  connection_timeout: 30s

discovery:
  type: "static"
  static:
    endpoints:

      # ── Local Ollama node (priority ${OLLA_LOCAL_PRIORITY}) ─────────────────
      - url: "http://ollama:11434"
        name: "ollama"
        type: "ollama"
        priority: ${OLLA_LOCAL_PRIORITY}
        check_interval: 15s
        check_timeout: 5s
EOF

# ── Remote LAN nodes ───────────────────────────────────────────────────────────
if [[ ${#REMOTE_URLS[@]} -gt 0 ]]; then
  echo "" >> "$OUTPUT"
  echo "      # ── Remote LAN nodes (from OLLAMA_REMOTE_* in .env) ────────────" >> "$OUTPUT"

  mapfile -t sorted_names < <(printf '%s\n' "${!REMOTE_URLS[@]}" | LC_ALL=C sort)
  for name in "${sorted_names[@]}"; do
    url="${REMOTE_URLS[$name]}"
    priority="${REMOTE_PRIORITIES[$name]}"
    display="${name,,}"

    cat >> "$OUTPUT" <<EOF

      - url: "${url}"
        name: "${display}"
        type: "ollama"
        priority: ${priority}
        check_interval: 20s
        check_timeout: 5s
EOF
    echo "   + ${display} → ${url} (priority ${priority})"
  done
fi

# ── Cloud gateway via LiteLLM ──────────────────────────────────────────────────
cat >> "$OUTPUT" <<EOF

      # ── Cloud gateway via LiteLLM (Claude, Gemini) ───────────────
      - url: "http://litellm:4000"
        name: "litellm-cloud"
        type: "litellm"
        priority: 50
        check_interval: 30s
        check_timeout: 10s

  model_discovery:
    enabled: true
    interval: 5m

logging:
  level: "info"
  format: "text"
EOF

echo "→ olla.yaml written to ${OUTPUT}"
