#!/usr/bin/env bash
# generate-olla-config.sh
#
# Generates olla.yaml from OLLAMA_REMOTE_* entries in .env.
# Called automatically by start.sh before docker compose up.
# Can also be run standalone to regenerate without restarting the stack.
#
# ── Remote node format in .env ────────────────────────────────────────────────
#
#   OLLAMA_REMOTE_<NAME>=<url>              # required — one line per node
#   OLLAMA_REMOTE_<NAME>_PRIORITY=<n>       # optional — defaults to 70
#
#   Examples:
#     OLLAMA_REMOTE_WORKSTATION=http://192.168.1.50:11434
#     OLLAMA_REMOTE_WORKSTATION_PRIORITY=75
#
#     OLLAMA_REMOTE_NAS=http://192.168.1.51:11434
#     # no priority set — will use default of 70
#
#   NAME can be anything alphanumeric + underscores. It becomes the node's
#   display name in Olla (lowercased, underscores preserved).
#
# ── Fixed nodes (always present, not configurable via .env) ──────────────────
#   priority 100 — ollama-arc   (local Intel Arc iGPU in Docker)
#   priority  50 — litellm      (cloud gateway: Claude, Gemini)
#
# ── Advanced tuning (optional .env vars) ─────────────────────────────────────
#   OLLA_ENGINE=sherpa              # or "olla" for circuit breakers + pooling
#   OLLA_LOAD_BALANCER=least-connections   # or "round-robin" / "priority"
#   OLLA_REQUEST_LOGGING=true

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${SCRIPT_DIR}/../proxy/olla.yaml"

# ── Load .env ─────────────────────────────────────────────────────────────────
if [[ -f "${SCRIPT_DIR}/../.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${SCRIPT_DIR}/../.env"
  set +a
fi

OLLA_ENGINE="${OLLA_ENGINE:-sherpa}"
OLLA_LOAD_BALANCER="${OLLA_LOAD_BALANCER:-least-connections}"
OLLA_REQUEST_LOGGING="${OLLA_REQUEST_LOGGING:-true}"

# ── Collect OLLAMA_REMOTE_* entries ──────────────────────────────────────────
# Reads NAME → URL pairs; looks up optional NAME_PRIORITY companion var.
declare -A REMOTE_URLS
declare -A REMOTE_PRIORITIES

while IFS='=' read -r key val; do
  # Match OLLAMA_REMOTE_<NAME> but NOT OLLAMA_REMOTE_<NAME>_PRIORITY
  [[ "$key" =~ ^OLLAMA_REMOTE_([A-Za-z0-9_]+)$ ]] || continue
  name="${BASH_REMATCH[1]}"
  # Strip inline comments and whitespace
  val="${val%%#*}"; val="${val#"${val%%[![:space:]]*}"}"; val="${val%"${val##*[![:space:]]}"}"
  [[ -n "$val" ]] || continue
  REMOTE_URLS["$name"]="$val"
  # Look up optional priority companion var
  priority_var="OLLAMA_REMOTE_${name}_PRIORITY"
  REMOTE_PRIORITIES["$name"]="${!priority_var:-70}"
done < "${SCRIPT_DIR}/../.env"

echo "→ Generating olla.yaml..."
if [[ ${#REMOTE_URLS[@]} -eq 0 ]]; then
  echo "   (no OLLAMA_REMOTE_* entries found — only local Arc node + LiteLLM)"
fi

# ── Write olla.yaml ───────────────────────────────────────────────────────────
cat > "${OUTPUT}" <<EOF
# olla.yaml — AUTO-GENERATED by generate-olla-config.sh
# Do not edit directly. Edit .env and re-run generate-olla-config.sh (or start.sh).
# This file is in .gitignore — LAN node addresses stay off the repo.
#
# Remote nodes are sourced from OLLAMA_REMOTE_* entries in .env.
# See generate-olla-config.sh header for the full format reference.
#
# Routing priority:
#   100 — ollama-arc        (local Intel Arc iGPU)
EOF

for name in "${!REMOTE_URLS[@]}"; do
  echo "#    ${REMOTE_PRIORITIES[$name]} — ${name,,}   (${REMOTE_URLS[$name]})" >> "${OUTPUT}"
done

cat >> "${OUTPUT}" <<EOF
#    50 — litellm-cloud     (Claude, Gemini via LiteLLM)

server:
  host: "0.0.0.0"
  port: 40114
  request_logging: ${OLLA_REQUEST_LOGGING}
  write_timeout: 600s

proxy:
  engine: "${OLLA_ENGINE}"
  load_balancer: "${OLLA_LOAD_BALANCER}"
  response_timeout: 600s
  connection_timeout: 30s

discovery:
  type: "static"
  static:
    endpoints:

      # ── Primary: local Intel Arc node ────────────────────────────────
      - url: "http://ollama-arc:11434"
        name: "ollama-arc-local"
        type: "ollama"
        priority: 100
        check_interval: 15s
        check_timeout: 5s
EOF

# ── Dynamic remote nodes ──────────────────────────────────────────────────────
if [[ ${#REMOTE_URLS[@]} -gt 0 ]]; then
  echo "" >> "${OUTPUT}"
  echo "      # ── Remote LAN nodes (from OLLAMA_REMOTE_* in .env) ────────────" >> "${OUTPUT}"

  for name in "${!REMOTE_URLS[@]}"; do
    url="${REMOTE_URLS[$name]}"
    priority="${REMOTE_PRIORITIES[$name]}"
    display="${name,,}"   # lowercase for YAML readability

    cat >> "${OUTPUT}" <<EOF

      - url: "${url}"
        name: "${display}"
        type: "ollama"
        priority: ${priority}
        check_interval: 20s
        check_timeout: 5s
EOF
    echo "   + ${display} → ${url} (priority ${priority})"
  done
fi

# ── Cloud gateway ─────────────────────────────────────────────────────────────
cat >> "${OUTPUT}" <<EOF

      # ── Cloud gateway via LiteLLM (Claude, Gemini) ───────────────────
      - url: "http://litellm:4000"
        name: "litellm-cloud"
        type: "litellm"
        priority: 50
        check_interval: 30s
        check_timeout: 10s

  model_discovery:
    enabled: true
    interval: 5m

logging:
  level: "info"
  format: "text"
EOF

echo "→ olla.yaml written to ${OUTPUT}"
